---
- name: Install base packages
  become: true
  apt:
    name:
      - ansible
      - vim
      - git
      - tmux
      - kitty

- name: Install i3 packages
  become: true
  apt:
    name:
      - i3
      - polybar

- name: Capture Tools
  become: true
  apt:
    name:
      - flameshot
      - peek
      - obs-studio
